apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: e19b9c7f7787d3f5958b856bd9961de5cf45a5ea65eb880b82cd8e4577190d70
    cni.projectcalico.org/podIP: 192.168.0.15/32
    cni.projectcalico.org/podIPs: 192.168.0.15/32
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "192.168.0.15"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "192.168.0.15"
          ],
          "default": true,
          "dns": {}
      }]
  creationTimestamp: "2024-02-20T06:11:31Z"
  generateName: example-webhook-77d4d7b57d-
  labels:
    app: example-webhook
    pod-template-hash: 77d4d7b57d
  name: example-webhook-77d4d7b57d-mk67l
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: example-webhook-77d4d7b57d
    uid: c4b0b090-3035-4911-8ca3-03ba0b707062
  uid: 9cb008c6-2c47-48ce-8390-6e6565b3226a
spec:
  containers:
  - image: 10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/enrich-cr-webhook:test
    imagePullPolicy: Always
    name: server
    ports:
    - containerPort: 8443
      name: tls
      protocol: TCP
    - containerPort: 80
      name: metrics
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/webhook/certs/
      name: example-webhook-tls-certs
      readOnly: true
    - mountPath: /etc/rules
      name: config-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-44gwf
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: abhi-master-node
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    runAsNonRoot: true
    runAsUser: 1234
  serviceAccount: example-webhook
  serviceAccountName: example-webhook
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: example-webhook-tls-certs
    secret:
      defaultMode: 420
      secretName: example-webhook-tls
  - configMap:
      defaultMode: 420
      name: enrich-cr-config
    name: config-volume
  - name: kube-api-access-44gwf
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-02-20T06:11:31Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-02-20T06:11:33Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-02-20T06:11:33Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-02-20T06:11:31Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://f193940be1468301f6ff719ed349007ce982ac32ba070c0b6de2e76ed420cec6
    image: 10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/enrich-cr-webhook:test
    imageID: 10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/enrich-cr-webhook@sha256:da5016757ca9cd6e47889d365897cd23ca394c4c4bcfbb5e32cb6586d6483474
    lastState: {}
    name: server
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-02-20T06:11:32Z"
  hostIP: 10.87.76.24
  phase: Running
  podIP: 192.168.0.15
  podIPs:
  - ip: 192.168.0.15
  qosClass: BestEffort
  startTime: "2024-02-20T06:11:31Z"
