apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 734ba7b3aca8e9660419d7a901f84d91d309c4e7c5fc80992ea46775548e74df
    cni.projectcalico.org/podIP: 192.168.0.27/32
    cni.projectcalico.org/podIPs: 192.168.0.27/32
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "192.168.0.27"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "192.168.0.27"
          ],
          "default": true,
          "dns": {}
      }]
  creationTimestamp: "2024-02-18T19:54:23Z"
  generateName: katafygio-74f4f998f5-
  labels:
    app: katafygio
    chart: katafygio-0.5.1
    heritage: Helm
    pod-template-hash: 74f4f998f5
    release: katafygio
  name: katafygio-74f4f998f5-2t2jw
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: katafygio-74f4f998f5
    uid: ec63fbfe-cd2b-4380-a901-ed46cf0296d5
  uid: 61e46055-6f27-4c79-ab4b-e4f66ff95717
spec:
  containers:
  - args:
    - --healthcheck-port=8080
    - --log-level=info
    - --log-output=stdout
    - --resync-interval=300
    - --exclude-kind=replicasets
    - --exclude-kind=endpoints
    - --exclude-kind=events
    image: 10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/katafygio-v3:CER-194
    imagePullPolicy: Always
    name: katafygio
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/katafygio
      name: katafygio-data
    - mountPath: /etc/katafygio
      name: config-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-tcfvs
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: abhi-master-node
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 65534
    runAsGroup: 65534
    runAsUser: 65534
  serviceAccount: katafygio
  serviceAccountName: katafygio
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: katafygio-data
    persistentVolumeClaim:
      claimName: katafygio
  - configMap:
      defaultMode: 420
      name: katafygio-config
    name: config-volume
  - name: kube-api-access-tcfvs
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-02-18T19:54:23Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-02-18T20:00:10Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-02-18T20:00:10Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-02-18T19:54:23Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://0215260afe8ccf10c848c67beb8596f41a04b77e93cc5752d371c5995b8aeb7f
    image: 10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/katafygio-v3:CER-194
    imageID: 10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/katafygio-v3@sha256:af2a7bdc908395bdd76974284a8915f5655438dd6ae300785a3e8db9f88abd0d
    lastState:
      terminated:
        containerID: cri-o://ec3ee12be4f9e2ce725e65199cc52f36cfd5611dd504393400a4d778b347e292
        exitCode: 1
        finishedAt: "2024-02-18T20:00:08Z"
        reason: Error
        startedAt: "2024-02-18T19:54:24Z"
    name: katafygio
    ready: true
    restartCount: 1
    started: true
    state:
      running:
        startedAt: "2024-02-18T20:00:09Z"
  hostIP: 10.87.76.24
  phase: Running
  podIP: 192.168.0.27
  podIPs:
  - ip: 192.168.0.27
  qosClass: BestEffort
  startTime: "2024-02-18T19:54:23Z"
