apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: d9e9a3f7287cf73e2e0eed76fe6c1bcb9610a1c83280b44375705cefb384b1e6
    cni.projectcalico.org/podIP: 192.168.0.20/32
    cni.projectcalico.org/podIPs: 192.168.0.20/32
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "192.168.0.20"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "192.168.0.20"
          ],
          "default": true,
          "dns": {}
      }]
  creationTimestamp: "2024-02-17T17:35:43Z"
  generateName: example-webhook-75bbd5d98b-
  labels:
    app: example-webhook
    pod-template-hash: 75bbd5d98b
  name: example-webhook-75bbd5d98b-5c5xk
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: example-webhook-75bbd5d98b
    uid: 28c58900-5ac0-4995-b538-7e97b16df34c
  uid: 38e39972-b985-4d01-8c27-9cef623d90cd
spec:
  containers:
  - image: svl-artifactory.juniper.net/atom-docker/cn2/sharmag07/mutatingwebhook:m9
    imagePullPolicy: IfNotPresent
    name: server
    ports:
    - containerPort: 8443
      name: tls
      protocol: TCP
    - containerPort: 80
      name: metrics
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/webhook/certs/
      name: example-webhook-tls-certs
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-lzgt9
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: abhi-master-node
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    runAsNonRoot: true
    runAsUser: 1234
  serviceAccount: example-webhook
  serviceAccountName: example-webhook
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: example-webhook-tls-certs
    secret:
      defaultMode: 420
      secretName: example-webhook-tls
  - name: kube-api-access-lzgt9
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-02-17T17:35:43Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-02-17T17:35:44Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-02-17T17:35:44Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-02-17T17:35:43Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://ae0171b9566211503724758b895562b82a2aafa2adaa26ce5c6c90aa3588dea4
    image: svl-artifactory.juniper.net/atom-docker/cn2/sharmag07/mutatingwebhook:m9
    imageID: svl-artifactory.juniper.net/atom-docker/cn2/sharmag07/mutatingwebhook@sha256:a4c3598356fea91152fa4d79450aef61ac2109796edb4ee4653a6eafe5b8e58c
    lastState: {}
    name: server
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-02-17T17:35:44Z"
  hostIP: 10.87.76.24
  phase: Running
  podIP: 192.168.0.20
  podIPs:
  - ip: 192.168.0.20
  qosClass: BestEffort
  startTime: "2024-02-17T17:35:43Z"
