apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: d1db36d3780a4c0039164baa92b4ac51ae09f947ef21fcff84ff64561dec7e27
    cni.projectcalico.org/podIP: 192.168.0.21/32
    cni.projectcalico.org/podIPs: 192.168.0.21/32
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "192.168.0.21"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "192.168.0.21"
          ],
          "default": true,
          "dns": {}
      }]
  creationTimestamp: "2024-02-17T17:29:17Z"
  generateName: enrich-cr-webhook-5b4cdb8fb4-
  labels:
    app: enrich-cr-webhook
    pod-template-hash: 5b4cdb8fb4
  name: enrich-cr-webhook-5b4cdb8fb4-gtk4c
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: enrich-cr-webhook-5b4cdb8fb4
    uid: 052eadb8-6664-48c0-a3d2-2a46a239acb9
  uid: f3bd44a1-a397-447f-bf98-e84686ceb73e
spec:
  containers:
  - image: svl-artifactory.juniper.net/atom-docker/cn2/sharmag07/mutatingwebhook:m9
    imagePullPolicy: IfNotPresent
    name: server
    ports:
    - containerPort: 8443
      name: tls
      protocol: TCP
    - containerPort: 80
      name: metrics
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/webhook/certs/
      name: enrich-cr-webhook-tls-certs
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-d9m97
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: abhi-master-node
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    runAsNonRoot: true
    runAsUser: 1234
  serviceAccount: enrich-cr-webhook
  serviceAccountName: enrich-cr-webhook
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: enrich-cr-webhook-tls-certs
    secret:
      defaultMode: 420
      secretName: enrich-cr-webhook-tls
  - name: kube-api-access-d9m97
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-02-17T17:29:17Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-02-17T17:29:17Z"
    message: 'containers with unready status: [server]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-02-17T17:29:17Z"
    message: 'containers with unready status: [server]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-02-17T17:29:17Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: svl-artifactory.juniper.net/atom-docker/cn2/sharmag07/mutatingwebhook:m9
    imageID: ""
    lastState: {}
    name: server
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        reason: ContainerCreating
  hostIP: 10.87.76.24
  phase: Pending
  qosClass: BestEffort
  startTime: "2024-02-17T17:29:17Z"
