apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 039626bd50dc789167846e2c846e188963a75c452238d9e2c88ab60e1971ad8f
    cni.projectcalico.org/podIP: 192.168.0.28/32
    cni.projectcalico.org/podIPs: 192.168.0.28/32
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "192.168.0.28"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "192.168.0.28"
          ],
          "default": true,
          "dns": {}
      }]
  creationTimestamp: "2024-02-18T19:56:00Z"
  generateName: example-webhook-75bbd5d98b-
  labels:
    app: example-webhook
    pod-template-hash: 75bbd5d98b
  name: example-webhook-75bbd5d98b-m5snz
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: example-webhook-75bbd5d98b
    uid: bd5ea992-4a6b-4cc8-9ced-03baa937fdc9
  uid: bd498114-4e13-40f4-93c8-2e55248851a0
spec:
  containers:
  - image: svl-artifactory.juniper.net/atom-docker/cn2/sharmag07/mutatingwebhook:m9
    imagePullPolicy: IfNotPresent
    name: server
    ports:
    - containerPort: 8443
      name: tls
      protocol: TCP
    - containerPort: 80
      name: metrics
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/webhook/certs/
      name: example-webhook-tls-certs
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-hjg7j
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: abhi-master-node
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    runAsNonRoot: true
    runAsUser: 1234
  serviceAccount: example-webhook
  serviceAccountName: example-webhook
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: example-webhook-tls-certs
    secret:
      defaultMode: 420
      secretName: example-webhook-tls
  - name: kube-api-access-hjg7j
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-02-18T19:56:00Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-02-18T19:56:01Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-02-18T19:56:01Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-02-18T19:56:00Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://c4dcafe5fe33f02dc21bfd9ba6fc89e028e6df7e2f7f29f9798eed6f87256d89
    image: svl-artifactory.juniper.net/atom-docker/cn2/sharmag07/mutatingwebhook:m9
    imageID: svl-artifactory.juniper.net/atom-docker/cn2/sharmag07/mutatingwebhook@sha256:a4c3598356fea91152fa4d79450aef61ac2109796edb4ee4653a6eafe5b8e58c
    lastState: {}
    name: server
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-02-18T19:56:01Z"
  hostIP: 10.87.76.24
  phase: Running
  podIP: 192.168.0.28
  podIPs:
  - ip: 192.168.0.28
  qosClass: BestEffort
  startTime: "2024-02-18T19:56:00Z"
