apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 8c948b095e28d4ad414a1132527d2c4dabf67143678f11f1b7aa2cba995e956d
    cni.projectcalico.org/podIP: 192.168.0.34/32
    cni.projectcalico.org/podIPs: 192.168.0.34/32
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "192.168.0.34"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "192.168.0.34"
          ],
          "default": true,
          "dns": {}
      }]
  creationTimestamp: "2024-02-19T05:53:16Z"
  generateName: example-webhook-57dd97598c-
  labels:
    app: example-webhook
    pod-template-hash: 57dd97598c
  name: example-webhook-57dd97598c-s7xcq
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: example-webhook-57dd97598c
    uid: 02ee021e-b835-40bf-b531-43e6697eef97
  uid: ed87d81d-92c2-47ea-a35c-18343d9d0d59
spec:
  containers:
  - image: 10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/enrich-cr-webhook:test
    imagePullPolicy: IfNotPresent
    name: server
    ports:
    - containerPort: 8443
      name: tls
      protocol: TCP
    - containerPort: 80
      name: metrics
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/webhook/certs/
      name: example-webhook-tls-certs
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-v26xp
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: abhi-master-node
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    runAsNonRoot: true
    runAsUser: 1234
  serviceAccount: example-webhook
  serviceAccountName: example-webhook
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: example-webhook-tls-certs
    secret:
      defaultMode: 420
      secretName: example-webhook-tls
  - name: kube-api-access-v26xp
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-02-19T05:53:16Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-02-19T05:53:16Z"
    message: 'containers with unready status: [server]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-02-19T05:53:16Z"
    message: 'containers with unready status: [server]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-02-19T05:53:16Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://1506dd5d94273ddc5f0467250d4d9f08658063b4cbc7130da93b97104b338c58
    image: 10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/enrich-cr-webhook:test
    imageID: 10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/enrich-cr-webhook@sha256:1ca1e6949daaf597156ed2ff139dacdfbd381095b94f37ec6ea58f917dcd6d07
    lastState:
      terminated:
        containerID: cri-o://c30bc21506e7dfda8dcc69a332c51b30e24e01e488f16418378a4ddf28cf321b
        exitCode: 1
        finishedAt: "2024-02-19T05:54:03Z"
        reason: Error
        startedAt: "2024-02-19T05:54:03Z"
    name: server
    ready: false
    restartCount: 4
    started: false
    state:
      terminated:
        containerID: cri-o://1506dd5d94273ddc5f0467250d4d9f08658063b4cbc7130da93b97104b338c58
        exitCode: 1
        finishedAt: "2024-02-19T05:54:56Z"
        reason: Error
        startedAt: "2024-02-19T05:54:56Z"
  hostIP: 10.87.76.24
  phase: Running
  podIP: 192.168.0.34
  podIPs:
  - ip: 192.168.0.34
  qosClass: BestEffort
  startTime: "2024-02-19T05:53:16Z"
