apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 983a5d06cce458bb81b60e273273955af06df2bafac901eab41776fb0afc3299
    cni.projectcalico.org/podIP: 192.168.0.5/32
    cni.projectcalico.org/podIPs: 192.168.0.5/32
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "192.168.0.5"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "192.168.0.5"
          ],
          "default": true,
          "dns": {}
      }]
  creationTimestamp: "2024-02-17T16:46:46Z"
  generateName: enrich-cr-webhook-c496448b4-
  labels:
    app: enrich-cr-webhook
    pod-template-hash: c496448b4
  name: enrich-cr-webhook-c496448b4-q8twz
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: enrich-cr-webhook-c496448b4
    uid: e1974373-47a0-49cc-b643-c72504c283fb
  uid: 3504c214-1c84-4710-a31c-bd6568f5b1ee
spec:
  containers:
  - image: 10.20.240.56:5000/atom-docker/cn2/bazel-build/dev/enrich-cr-webhook:CER-194
    imagePullPolicy: IfNotPresent
    name: server
    ports:
    - containerPort: 8443
      name: tls
      protocol: TCP
    - containerPort: 80
      name: metrics
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/webhook/certs/
      name: enrich-cr-webhook-tls-certs
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-f9495
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: abhi-master-node
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    runAsNonRoot: true
    runAsUser: 1234
  serviceAccount: enrich-cr-webhook
  serviceAccountName: enrich-cr-webhook
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: enrich-cr-webhook-tls-certs
    secret:
      defaultMode: 420
      secretName: enrich-cr-webhook-tls
  - name: kube-api-access-f9495
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-02-17T16:46:46Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-02-17T16:46:46Z"
    message: 'containers with unready status: [server]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-02-17T16:46:46Z"
    message: 'containers with unready status: [server]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-02-17T16:46:46Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: 10.20.240.56:5000/atom-docker/cn2/bazel-build/dev/enrich-cr-webhook:CER-194
    imageID: ""
    lastState: {}
    name: server
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        reason: ContainerCreating
  hostIP: 10.87.76.24
  phase: Pending
  qosClass: BestEffort
  startTime: "2024-02-17T16:46:46Z"
