apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: bffff3503b708c73a3158ac296a9a03acec41a28738a5383f36faa61b55c70ba
    cni.projectcalico.org/podIP: 192.168.0.22/32
    cni.projectcalico.org/podIPs: 192.168.0.22/32
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "192.168.0.22"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "192.168.0.22"
          ],
          "default": true,
          "dns": {}
      }]
  creationTimestamp: "2024-02-19T19:27:11Z"
  generateName: example-webhook-6cc74f7d84-
  labels:
    app: example-webhook
    pod-template-hash: 6cc74f7d84
  name: example-webhook-6cc74f7d84-jfp9r
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: example-webhook-6cc74f7d84
    uid: 26b4e4c6-fbd8-4fc1-a880-e8cc6c0117dc
  uid: e87c36be-b911-40b2-a1a5-b4a12006d368
spec:
  containers:
  - image: svl-artifactory.juniper.net/atom-docker/cn2/trohit7/webhook:withrules
    imagePullPolicy: IfNotPresent
    name: server
    ports:
    - containerPort: 8443
      name: tls
      protocol: TCP
    - containerPort: 80
      name: metrics
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/webhook/certs/
      name: example-webhook-tls-certs
      readOnly: true
    - mountPath: /etc/rules
      name: config-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-ttr8w
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: abhi-master-node
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    runAsNonRoot: true
    runAsUser: 1234
  serviceAccount: example-webhook
  serviceAccountName: example-webhook
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: example-webhook-tls-certs
    secret:
      defaultMode: 420
      secretName: example-webhook-tls
  - configMap:
      defaultMode: 420
      name: enrich-cr-config
    name: config-volume
  - name: kube-api-access-ttr8w
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-02-19T19:27:11Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-02-19T19:27:15Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-02-19T19:27:15Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-02-19T19:27:11Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://ed138788f8607c67a5dbce7dc6d50c107b2c0eabec554d20cc321995d33e41ba
    image: svl-artifactory.juniper.net/atom-docker/cn2/trohit7/webhook:withrules
    imageID: svl-artifactory.juniper.net/atom-docker/cn2/trohit7/webhook@sha256:bfc5375626ccd977a91b4c0fdeb34f2025b6da2e3ab5783401d1fa0d0c7b5d80
    lastState: {}
    name: server
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-02-19T19:27:14Z"
  hostIP: 10.87.76.24
  phase: Running
  podIP: 192.168.0.22
  podIPs:
  - ip: 192.168.0.22
  qosClass: BestEffort
  startTime: "2024-02-19T19:27:11Z"
