apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"enrich-cr-webhook","namespace":"default"},"spec":{"ports":[{"name":"application","port":443,"targetPort":8443},{"name":"metrics","port":80,"targetPort":"metrics"}],"selector":{"app":"enrich-cr-webhook"}}}
  creationTimestamp: "2024-02-17T14:49:33Z"
  name: enrich-cr-webhook
  namespace: default
  uid: c097402d-9b3f-496c-93bc-84ede38bf623
spec:
  clusterIP: 10.99.7.38
  clusterIPs:
  - 10.99.7.38
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: application
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: metrics
    port: 80
    protocol: TCP
    targetPort: metrics
  selector:
    app: enrich-cr-webhook
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
