apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"example-webhook","namespace":"default"},"spec":{"ports":[{"name":"application","port":443,"targetPort":8443},{"name":"metrics","port":80,"targetPort":"metrics"}],"selector":{"app":"example-webhook"}}}
  creationTimestamp: "2024-02-20T04:07:39Z"
  name: example-webhook
  namespace: default
  uid: 9af124e1-9c43-4857-9562-ffa8812b8ee6
spec:
  clusterIP: 10.107.186.248
  clusterIPs:
  - 10.107.186.248
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: application
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: metrics
    port: 80
    protocol: TCP
    targetPort: metrics
  selector:
    app: example-webhook
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
