apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"example-webhook","namespace":"default"},"spec":{"ports":[{"name":"application","port":443,"targetPort":8443},{"name":"metrics","port":80,"targetPort":"metrics"}],"selector":{"app":"example-webhook"}}}
  creationTimestamp: "2024-02-19T16:11:23Z"
  name: example-webhook
  namespace: default
  uid: d7c344e8-9d0b-4045-8d15-4c4fcb7fd84e
spec:
  clusterIP: 10.103.36.40
  clusterIPs:
  - 10.103.36.40
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: application
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: metrics
    port: 80
    protocol: TCP
    targetPort: metrics
  selector:
    app: example-webhook
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
