apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"testservice","namespace":"default"},"spec":{"ports":[{"nodePort":30037,"port":3000,"protocol":"TCP","targetPort":3000}],"selector":{"app":"test"},"type":"NodePort"}}
  creationTimestamp: "2024-02-18T08:55:17Z"
  name: testservice
  namespace: default
  uid: c6b39dff-ef90-493e-9790-fe1de8141e91
spec:
  clusterIP: 10.106.226.219
  clusterIPs:
  - 10.106.226.219
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30037
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: test
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
